### ISSUE TITLE
请问知道如何调整金币爆率么？

### ISSUE THREAD

**Issue by Shimada666** [XanderYe/dnf#5]
我使用了本项目启动 dnf 服务端 + 本项目提供的 dnf 客户端 + 本项目提供的 dof 补丁，项目成功起起来了。但是实际游戏过程中发现金币爆率好像特别高，格兰之森的地图翻牌能出 3000 金币，地上掉的金币也特别多。查看 pvf 的 etc/itemdrop common 文件之后发现金币爆率也是正常的 (1 19 5...)，请问知道如何把金币爆率调到正常么

**Comment by XanderYe** [comment]
不知道诶，很久没研究了，建议加群问大佬
